/*
 * SPDX-FileCopyrightText: 2018-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/*
* Change Logs:
* Date			 Author 	  Notes
* 2024-09-26	 Beken	  adapter to Beken sdk
* 2024-10-15     Beken    change mbedtls_ssl_conf_verify to change mbedtls_ssl_conf_ca_cb
*/
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include "esp_crt_bundle.h"
#define TAG "CRT_BUNDLE"

#define BUNDLE_HEADER_OFFSET 2
#define CRT_HEADER_OFFSET 4

extern const uint8_t x509_crt_imported_bundle_bin_start[] asm("_binary_x509_crt_bundle_start");
extern const uint8_t x509_crt_imported_bundle_bin_end[]   asm("_binary_x509_crt_bundle_end");


typedef struct crt_bundle_t {
    const uint8_t **crts;
    uint16_t num_certs;
    size_t x509_crt_bundle_len;
} crt_bundle_t;

static crt_bundle_t s_crt_bundle;

static int _crt_bundle_mbedtls_x509_crt_load(mbedtls_x509_crt *crt, const uint8_t *name, size_t name_len, const uint8_t *key, size_t key_len) {
    unsigned char *p = (unsigned char *)name;
    size_t len;
    int ret = mbedtls_asn1_get_tag(&p, p + name_len, &len, MBEDTLS_ASN1_CONSTRUCTED | MBEDTLS_ASN1_SEQUENCE);
    if (ret != 0) {
        BK_LOGE(TAG, "Load cert - mbedtls_asn1_get_tag error %#x", -ret);
        return ret;
    }
    ret = mbedtls_x509_get_name(&p, p + len, &crt->subject);
    if (ret != 0) {
        BK_LOGE(TAG, "Load cert - mbedtls_x509_get_name error %#x", -ret);
        return ret;
    }
    ret = mbedtls_pk_parse_public_key(&crt->pk, key, key_len);
    if (ret != 0) {
        BK_LOGE(TAG, "Load cert - mbedtls_pk_parse_public_key error %#x", -ret);
        return ret;
    }
    return 0;
}

/* This callback is called for every certificate in the chain.
*  Find the store crt and load candidate CAs.
*/
static int _crt_bundle_mbedtls_x509_crt_ca_cb(void *buf, mbedtls_x509_crt const *child, mbedtls_x509_crt **candidate_cas)
{
    if (s_crt_bundle.crts == NULL) {
        BK_LOGE(TAG, "No certificates in bundle");
        return MBEDTLS_ERR_X509_FATAL_ERROR;
    }

    BK_LOGD(TAG, "%d certificates in bundle", s_crt_bundle.num_certs);

    mbedtls_x509_crt *first = calloc(1, sizeof(mbedtls_x509_crt));
    mbedtls_x509_crt_init(first);

    size_t name_len = 0;
    const uint8_t *crt_name;

    bool crt_found = false;
    int start = 0;
    int end = s_crt_bundle.num_certs - 1;
    int middle = (end - start) / 2;

    /* Look for the certificate using binary search on subject name */
    while (start <= end) {
        name_len = s_crt_bundle.crts[middle][0] << 8 | s_crt_bundle.crts[middle][1];
        crt_name = s_crt_bundle.crts[middle] + CRT_HEADER_OFFSET;

        int cmp_res = memcmp(child->issuer_raw.p, crt_name, name_len );
        if (cmp_res == 0) {
            crt_found = true;
            break;
        } else if (cmp_res < 0) {
            end = middle - 1;
        } else {
            start = middle + 1;
        }
        middle = (start + end) / 2;
    }

    int ret = MBEDTLS_ERR_X509_FATAL_ERROR;
    if (crt_found) {
        const uint8_t *key = s_crt_bundle.crts[middle] + CRT_HEADER_OFFSET + name_len;
        size_t key_len = s_crt_bundle.crts[middle][2] << 8 | s_crt_bundle.crts[middle][3];
        ret = _crt_bundle_mbedtls_x509_crt_load(first, crt_name, name_len, key, key_len);
        if (ret !=0) {
            mbedtls_x509_crt_free(first);
            free(first);
            return MBEDTLS_ERR_X509_FATAL_ERROR;
        }
    }

    *candidate_cas = first;
    return 0;
}


/* Initialize the bundle into an array so we can do binary search for certs,
   the bundle generated by the python utility is already presorted by subject name
 */
static bk_err_t esp_crt_bundle_init(const uint8_t *x509_bundle, size_t bundle_size)
{
    if (bundle_size < BUNDLE_HEADER_OFFSET + CRT_HEADER_OFFSET) {
        BK_LOGE(TAG, "Invalid certificate bundle");
        return -1;
    }

    uint16_t num_certs = (x509_bundle[0] << 8) | x509_bundle[1];
    if (num_certs > CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS) {
        BK_LOGE(TAG, "No. of certs in the certificate bundle = %d exceeds\n"
                      "Max allowed certificates in the certificate bundle = %d\n"
                      "Please update the menuconfig option with appropriate value", num_certs, CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_MAX_CERTS);
        return -1;
    }

    const uint8_t **crts = calloc(num_certs, sizeof(x509_bundle));
    if (crts == NULL) {
        BK_LOGE(TAG, "Unable to allocate memory for bundle");
        return BK_ERR_NO_MEM;
    }

    const uint8_t *cur_crt;
    /* This is the maximum region that is allowed to access */
    const uint8_t *bundle_end = x509_bundle + bundle_size;
    cur_crt = x509_bundle + BUNDLE_HEADER_OFFSET;

    for (int i = 0; i < num_certs; i++) {
        crts[i] = cur_crt;
        if (cur_crt + CRT_HEADER_OFFSET > bundle_end) {
            BK_LOGE(TAG, "Invalid certificate bundle");
            free(crts);
            return -1;
        }
        size_t name_len = cur_crt[0] << 8 | cur_crt[1];
        size_t key_len = cur_crt[2] << 8 | cur_crt[3];
        cur_crt = cur_crt + CRT_HEADER_OFFSET + name_len + key_len;
    }

    if (cur_crt > bundle_end) {
        BK_LOGE(TAG, "Invalid certificate bundle");
        free(crts);
        return -1;
    }

    /* The previous crt bundle is only updated when initialization of the
     * current crt_bundle is successful */
    /* Free previous crt_bundle */
    free(s_crt_bundle.crts);
    s_crt_bundle.num_certs = num_certs;
    s_crt_bundle.crts = crts;
    return BK_OK;
}

bk_err_t esp_crt_bundle_attach(void *conf)
{
    bk_err_t ret = BK_OK;
    // If no bundle has been set by the user then use the bundle embedded in the binary
    if (s_crt_bundle.crts == NULL) {
        ret = esp_crt_bundle_init(x509_crt_imported_bundle_bin_start, x509_crt_imported_bundle_bin_end - x509_crt_imported_bundle_bin_start);
    }

    if (ret != BK_OK) {
        BK_LOGE(TAG, "Failed to attach bundle");
        return ret;
    }

    if (conf) {
        /* point to a dummy certificate
         * This is only required so that the
         * cacert_ptr passes non-NULL check during handshake
         */
        mbedtls_ssl_config *ssl_conf = (mbedtls_ssl_config *)conf;
        mbedtls_ssl_conf_ca_cb(ssl_conf, _crt_bundle_mbedtls_x509_crt_ca_cb, NULL);
    }

    return ret;
}

void esp_crt_bundle_detach(mbedtls_ssl_config *conf)
{
    free(s_crt_bundle.crts);
    s_crt_bundle.crts = NULL;
    if (conf) {
        mbedtls_ssl_conf_ca_cb(conf, NULL, NULL);
    }
}

bk_err_t esp_crt_bundle_set(const uint8_t *x509_bundle, size_t bundle_size)
{
    return esp_crt_bundle_init(x509_bundle, bundle_size);
}
