set(MESH_MACRO_CONFIG
    CONFIG_ACLSEMI_BT_MESH_LOOPBACK=0
    CONFIG_ACLSEMI_BTC_FEATURE_INCLUDED=1
)

if (CONFIG_BT_MESH_SETTINGS)
    list(APPEND MESH_MACRO_CONFIG
        CONFIG_BT_SETTINGS=1
    )
endif()

if (CONFIG_BT_MESH_SMP)
    list(APPEND MESH_MACRO_CONFIG
        CONFIG_BT_SMP=1
    )
endif()

if (CONFIG_BT_MESH_CONN)
    list(APPEND MESH_MACRO_CONFIG
        CONFIG_BT_CONN=1
        CONFIG_BT_GATT_DYNAMIC_DB=1
        CONFIG_BT_GATT_SERVICE_CHANGED=1
    )
endif()

if (CONFIG_BT_MESH_GATT_PROXY)
    list(APPEND MESH_MACRO_CONFIG
        CONFIG_BT_MESH_PROXY=1)
endif()
