// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define SCR_DEVICEID_ADDR (SOC_SCR_REG_BASE + (0x0 << 2))

#define SCR_DEVICEID_DEVICEID_POS (0)
#define SCR_DEVICEID_DEVICEID_MASK (0xffffffff)

#define SCR_VERSIONID_ADDR (SOC_SCR_REG_BASE + (0x1 << 2))

#define SCR_VERSIONID_VERSIONID_POS (0)
#define SCR_VERSIONID_VERSIONID_MASK (0xffffffff)

#define SCR_GLOBAL_CTRL_ADDR (SOC_SCR_REG_BASE + (0x2 << 2))

#define SCR_GLOBAL_CTRL_SOFT_RST_POS (0)
#define SCR_GLOBAL_CTRL_SOFT_RST_MASK (0x1)

#define SCR_GLOBAL_CTRL_BYPASS_CKG_POS (1)
#define SCR_GLOBAL_CTRL_BYPASS_CKG_MASK (0x1)

#define SCR_GLOBAL_CTRL_RESERVED_BIT_2_31_POS (2)
#define SCR_GLOBAL_CTRL_RESERVED_BIT_2_31_MASK (0x3fffffff)

#define SCR_GLOBAL_STATUS_ADDR (SOC_SCR_REG_BASE + (0x3 << 2))

#define SCR_GLOBAL_STATUS_GLOBAL_STATUS_POS (0)
#define SCR_GLOBAL_STATUS_GLOBAL_STATUS_MASK (0xffffffff)

#define SCR_CTRL1_ADDR (SOC_SCR_REG_BASE + (0x4 << 2))

#define SCR_CTRL1_INVLEV_POS (0)
#define SCR_CTRL1_INVLEV_MASK (0x1)

#define SCR_CTRL1_INVORD_POS (1)
#define SCR_CTRL1_INVORD_MASK (0x1)

#define SCR_CTRL1_PECH2FIFO_POS (2)
#define SCR_CTRL1_PECH2FIFO_MASK (0x1)

#define SCR_CTRL1_RESERVED_3_5_POS (3)
#define SCR_CTRL1_RESERVED_3_5_MASK (0x7)

#define SCR_CTRL1_CLKSTOP_POS (6)
#define SCR_CTRL1_CLKSTOP_MASK (0x1)

#define SCR_CTRL1_CLKSTOPVAL_POS (7)
#define SCR_CTRL1_CLKSTOPVAL_MASK (0x1)

#define SCR_CTRL1_TXEN_POS (8)
#define SCR_CTRL1_TXEN_MASK (0x1)

#define SCR_CTRL1_RXEN_POS (9)
#define SCR_CTRL1_RXEN_MASK (0x1)

#define SCR_CTRL1_TS2FIFO_POS (10)
#define SCR_CTRL1_TS2FIFO_MASK (0x1)

#define SCR_CTRL1_T0T1_POS (11)
#define SCR_CTRL1_T0T1_MASK (0x1)

#define SCR_CTRL1_ATRSTFLUSH_POS (12)
#define SCR_CTRL1_ATRSTFLUSH_MASK (0x1)

#define SCR_CTRL1_TCKEN_POS (13)
#define SCR_CTRL1_TCKEN_MASK (0x1)

#define SCR_CTRL1_RESERVED_14_14_POS (14)
#define SCR_CTRL1_RESERVED_14_14_MASK (0x1)

#define SCR_CTRL1_GINTEN_POS (15)
#define SCR_CTRL1_GINTEN_MASK (0x1)

#define SCR_CTRL1_RESERVED_BIT_16_31_POS (16)
#define SCR_CTRL1_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_CTRL2_ADDR (SOC_SCR_REG_BASE + (0x5 << 2))

#define SCR_CTRL2_RESERVED_0_0_POS (0)
#define SCR_CTRL2_RESERVED_0_0_MASK (0x1)

#define SCR_CTRL2_RESERVED_1_1_POS (1)
#define SCR_CTRL2_RESERVED_1_1_MASK (0x1)

#define SCR_CTRL2_WARMRST_POS (2)
#define SCR_CTRL2_WARMRST_MASK (0x1)

#define SCR_CTRL2_ACT_POS (3)
#define SCR_CTRL2_ACT_MASK (0x1)

#define SCR_CTRL2_DEACT_POS (4)
#define SCR_CTRL2_DEACT_MASK (0x1)

#define SCR_CTRL2_VCC18_POS (5)
#define SCR_CTRL2_VCC18_MASK (0x1)

#define SCR_CTRL2_VCC30_POS (6)
#define SCR_CTRL2_VCC30_MASK (0x1)

#define SCR_CTRL2_VCC50_POS (7)
#define SCR_CTRL2_VCC50_MASK (0x1)

#define SCR_CTRL2_ACT_FAST_POS (8)
#define SCR_CTRL2_ACT_FAST_MASK (0x1)

#define SCR_CTRL2_RESERVED_9_15_POS (9)
#define SCR_CTRL2_RESERVED_9_15_MASK (0x7f)

#define SCR_CTRL2_RESERVED_BIT_16_31_POS (16)
#define SCR_CTRL2_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_SCPADS_ADDR (SOC_SCR_REG_BASE + (0x6 << 2))

#define SCR_SCPADS_DIRACCPADS_POS (0)
#define SCR_SCPADS_DIRACCPADS_MASK (0x1)

#define SCR_SCPADS_DSCIO_POS (1)
#define SCR_SCPADS_DSCIO_MASK (0x1)

#define SCR_SCPADS_DSCCLK_POS (2)
#define SCR_SCPADS_DSCCLK_MASK (0x1)

#define SCR_SCPADS_DSCRST_POS (3)
#define SCR_SCPADS_DSCRST_MASK (0x1)

#define SCR_SCPADS_DSCVCC_POS (4)
#define SCR_SCPADS_DSCVCC_MASK (0x1)

#define SCR_SCPADS_AUTOADEAVPP_POS (5)
#define SCR_SCPADS_AUTOADEAVPP_MASK (0x1)

#define SCR_SCPADS_DSCVPPEN_POS (6)
#define SCR_SCPADS_DSCVPPEN_MASK (0x1)

#define SCR_SCPADS_DSCVPPPP_POS (7)
#define SCR_SCPADS_DSCVPPPP_MASK (0x1)

#define SCR_SCPADS_DSCFCB_POS (8)
#define SCR_SCPADS_DSCFCB_MASK (0x1)

#define SCR_SCPADS_SCPRESENT_POS (9)
#define SCR_SCPADS_SCPRESENT_MASK (0x1)

#define SCR_SCPADS_RESERVED_10_15_POS (10)
#define SCR_SCPADS_RESERVED_10_15_MASK (0x3f)

#define SCR_SCPADS_RESERVED_BIT_16_31_POS (16)
#define SCR_SCPADS_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_INTEN1_ADDR (SOC_SCR_REG_BASE + (0x7 << 2))

#define SCR_INTEN1_TXFIDONE_POS (0)
#define SCR_INTEN1_TXFIDONE_MASK (0x1)

#define SCR_INTEN1_TXFIEMPTY_POS (1)
#define SCR_INTEN1_TXFIEMPTY_MASK (0x1)

#define SCR_INTEN1_RXFIFULL_POS (2)
#define SCR_INTEN1_RXFIFULL_MASK (0x1)

#define SCR_INTEN1_CLKSTOPRUN_POS (3)
#define SCR_INTEN1_CLKSTOPRUN_MASK (0x1)

#define SCR_INTEN1_TXDONE_POS (4)
#define SCR_INTEN1_TXDONE_MASK (0x1)

#define SCR_INTEN1_RXDONE_POS (5)
#define SCR_INTEN1_RXDONE_MASK (0x1)

#define SCR_INTEN1_TXPERR_POS (6)
#define SCR_INTEN1_TXPERR_MASK (0x1)

#define SCR_INTEN1_RXPERR_POS (7)
#define SCR_INTEN1_RXPERR_MASK (0x1)

#define SCR_INTEN1_C2CFULL_POS (8)
#define SCR_INTEN1_C2CFULL_MASK (0x1)

#define SCR_INTEN1_RXTHRESHOLD_POS (9)
#define SCR_INTEN1_RXTHRESHOLD_MASK (0x1)

#define SCR_INTEN1_ATRFAIL_POS (10)
#define SCR_INTEN1_ATRFAIL_MASK (0x1)

#define SCR_INTEN1_ATRDONE_POS (11)
#define SCR_INTEN1_ATRDONE_MASK (0x1)

#define SCR_INTEN1_SCREM_POS (12)
#define SCR_INTEN1_SCREM_MASK (0x1)

#define SCR_INTEN1_SCINS_POS (13)
#define SCR_INTEN1_SCINS_MASK (0x1)

#define SCR_INTEN1_SCACT_POS (14)
#define SCR_INTEN1_SCACT_MASK (0x1)

#define SCR_INTEN1_SCDEACT_POS (15)
#define SCR_INTEN1_SCDEACT_MASK (0x1)

#define SCR_INTEN1_RESERVED_BIT_16_31_POS (16)
#define SCR_INTEN1_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_INTSTAT1_ADDR (SOC_SCR_REG_BASE + (0x8 << 2))

#define SCR_INTSTAT1_TXFIDONE_POS (0)
#define SCR_INTSTAT1_TXFIDONE_MASK (0x1)

#define SCR_INTSTAT1_TXFIEMPTY_POS (1)
#define SCR_INTSTAT1_TXFIEMPTY_MASK (0x1)

#define SCR_INTSTAT1_RXFIFULL_POS (2)
#define SCR_INTSTAT1_RXFIFULL_MASK (0x1)

#define SCR_INTSTAT1_CLKSTOPRUN_POS (3)
#define SCR_INTSTAT1_CLKSTOPRUN_MASK (0x1)

#define SCR_INTSTAT1_TXDONE_POS (4)
#define SCR_INTSTAT1_TXDONE_MASK (0x1)

#define SCR_INTSTAT1_RXDONE_POS (5)
#define SCR_INTSTAT1_RXDONE_MASK (0x1)

#define SCR_INTSTAT1_TXPERR_POS (6)
#define SCR_INTSTAT1_TXPERR_MASK (0x1)

#define SCR_INTSTAT1_RXPERR_POS (7)
#define SCR_INTSTAT1_RXPERR_MASK (0x1)

#define SCR_INTSTAT1_C2CFULL_POS (8)
#define SCR_INTSTAT1_C2CFULL_MASK (0x1)

#define SCR_INTSTAT1_RXTHRESHOLD_POS (9)
#define SCR_INTSTAT1_RXTHRESHOLD_MASK (0x1)

#define SCR_INTSTAT1_ATRFAIL_POS (10)
#define SCR_INTSTAT1_ATRFAIL_MASK (0x1)

#define SCR_INTSTAT1_ATRDONE_POS (11)
#define SCR_INTSTAT1_ATRDONE_MASK (0x1)

#define SCR_INTSTAT1_SCREM_POS (12)
#define SCR_INTSTAT1_SCREM_MASK (0x1)

#define SCR_INTSTAT1_SCINS_POS (13)
#define SCR_INTSTAT1_SCINS_MASK (0x1)

#define SCR_INTSTAT1_SCACT_POS (14)
#define SCR_INTSTAT1_SCACT_MASK (0x1)

#define SCR_INTSTAT1_SCDEACT_POS (15)
#define SCR_INTSTAT1_SCDEACT_MASK (0x1)

#define SCR_INTSTAT1_RESERVED_BIT_16_31_POS (16)
#define SCR_INTSTAT1_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_FIFOCTRL_ADDR (SOC_SCR_REG_BASE + (0x9 << 2))

#define SCR_FIFOCTRL_TXFIEMPTY_POS (0)
#define SCR_FIFOCTRL_TXFIEMPTY_MASK (0x1)

#define SCR_FIFOCTRL_TXFIFULL_POS (1)
#define SCR_FIFOCTRL_TXFIFULL_MASK (0x1)

#define SCR_FIFOCTRL_TXFIFLUSH_POS (2)
#define SCR_FIFOCTRL_TXFIFLUSH_MASK (0x1)

#define SCR_FIFOCTRL_RESERVED_3_7_POS (3)
#define SCR_FIFOCTRL_RESERVED_3_7_MASK (0x1f)

#define SCR_FIFOCTRL_RXFIEMPTY_POS (8)
#define SCR_FIFOCTRL_RXFIEMPTY_MASK (0x1)

#define SCR_FIFOCTRL_RXFIFULL_POS (9)
#define SCR_FIFOCTRL_RXFIFULL_MASK (0x1)

#define SCR_FIFOCTRL_RXFIFLUSH_POS (10)
#define SCR_FIFOCTRL_RXFIFLUSH_MASK (0x1)

#define SCR_FIFOCTRL_RESERVED_11_15_POS (11)
#define SCR_FIFOCTRL_RESERVED_11_15_MASK (0x1f)

#define SCR_FIFOCTRL_RESERVED_BIT_16_31_POS (16)
#define SCR_FIFOCTRL_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_LEGACY_RX_FIFO_COUNTER_ADDR (SOC_SCR_REG_BASE + (0xa << 2))

#define SCR_LEGACY_RX_FIFO_COUNTER_LEGACY_RX_FIFO_CNT_POS (0)
#define SCR_LEGACY_RX_FIFO_COUNTER_LEGACY_RX_FIFO_CNT_MASK (0xff)

#define SCR_LEGACY_RX_FIFO_COUNTER_LEGACY_TX_FIFO_CNT_POS (8)
#define SCR_LEGACY_RX_FIFO_COUNTER_LEGACY_TX_FIFO_CNT_MASK (0xff)

#define SCR_LEGACY_RX_FIFO_COUNTER_RESERVED_BIT_16_31_POS (16)
#define SCR_LEGACY_RX_FIFO_COUNTER_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_RX_FIFO_THRESHOLD_ADDR (SOC_SCR_REG_BASE + (0xb << 2))

#define SCR_RX_FIFO_THRESHOLD_RX_FIFO_THD_POS (0)
#define SCR_RX_FIFO_THRESHOLD_RX_FIFO_THD_MASK (0xffff)

#define SCR_RX_FIFO_THRESHOLD_RESERVED_BIT_16_31_POS (16)
#define SCR_RX_FIFO_THRESHOLD_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_TX_REPEAT_ADDR (SOC_SCR_REG_BASE + (0xc << 2))

#define SCR_TX_REPEAT_TX_REPEAT_POS (0)
#define SCR_TX_REPEAT_TX_REPEAT_MASK (0xf)

#define SCR_TX_REPEAT_RX_REPEAT_POS (4)
#define SCR_TX_REPEAT_RX_REPEAT_MASK (0xf)

#define SCR_TX_REPEAT_RESERVED_8_15_POS (8)
#define SCR_TX_REPEAT_RESERVED_8_15_MASK (0xff)

#define SCR_TX_REPEAT_RESERVED_BIT_16_31_POS (16)
#define SCR_TX_REPEAT_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_SMART_CARD_CLOCK_DIVISOR_ADDR (SOC_SCR_REG_BASE + (0xd << 2))

#define SCR_SMART_CARD_CLOCK_DIVISOR_SMART_CARD_CLK_DIV_POS (0)
#define SCR_SMART_CARD_CLOCK_DIVISOR_SMART_CARD_CLK_DIV_MASK (0xffff)

#define SCR_SMART_CARD_CLOCK_DIVISOR_RESERVED_BIT_16_31_POS (16)
#define SCR_SMART_CARD_CLOCK_DIVISOR_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_BAUD_CLOCK_DIVISOR_ADDR (SOC_SCR_REG_BASE + (0xe << 2))

#define SCR_BAUD_CLOCK_DIVISOR_BAND_CLK_DIV_POS (0)
#define SCR_BAUD_CLOCK_DIVISOR_BAND_CLK_DIV_MASK (0xffff)

#define SCR_BAUD_CLOCK_DIVISOR_RESERVED_BIT_16_31_POS (16)
#define SCR_BAUD_CLOCK_DIVISOR_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_SMART_CARD_GUARDTIME_ADDR (SOC_SCR_REG_BASE + (0xf << 2))

#define SCR_SMART_CARD_GUARDTIME_SMART_CARD_GUARDTIME_POS (0)
#define SCR_SMART_CARD_GUARDTIME_SMART_CARD_GUARDTIME_MASK (0xff)

#define SCR_SMART_CARD_GUARDTIME_RESERVED_8_15_POS (8)
#define SCR_SMART_CARD_GUARDTIME_RESERVED_8_15_MASK (0xff)

#define SCR_SMART_CARD_GUARDTIME_RESERVED_BIT_16_31_POS (16)
#define SCR_SMART_CARD_GUARDTIME_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_ACTIVATION_DEACTIVATION_TIME_ADDR (SOC_SCR_REG_BASE + (0x10 << 2))

#define SCR_ACTIVATION_DEACTIVATION_TIME_ACTIVATION_TIME_POS (0)
#define SCR_ACTIVATION_DEACTIVATION_TIME_ACTIVATION_TIME_MASK (0xffff)

#define SCR_ACTIVATION_DEACTIVATION_TIME_RESERVED_BIT_16_31_POS (16)
#define SCR_ACTIVATION_DEACTIVATION_TIME_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_RESET_DURATION_ADDR (SOC_SCR_REG_BASE + (0x11 << 2))

#define SCR_RESET_DURATION_RESET_DURATION_POS (0)
#define SCR_RESET_DURATION_RESET_DURATION_MASK (0xffff)

#define SCR_RESET_DURATION_RESERVED_BIT_16_31_POS (16)
#define SCR_RESET_DURATION_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_ATR_START_LIMIT_ADDR (SOC_SCR_REG_BASE + (0x12 << 2))

#define SCR_ATR_START_LIMIT_ATR_START_LIMIT_POS (0)
#define SCR_ATR_START_LIMIT_ATR_START_LIMIT_MASK (0xffff)

#define SCR_ATR_START_LIMIT_RESERVED_BIT_16_31_POS (16)
#define SCR_ATR_START_LIMIT_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_L_ADDR (SOC_SCR_REG_BASE + (0x13 << 2))

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_L_TWO_CHAR_DELAY_LIMIT_L_POS (0)
#define SCR_TWO_CHARACTERS_DELAY_LIMIT_L_TWO_CHAR_DELAY_LIMIT_L_MASK (0xffff)

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_L_RESERVED_BIT_16_31_POS (16)
#define SCR_TWO_CHARACTERS_DELAY_LIMIT_L_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_INTEN2_ADDR (SOC_SCR_REG_BASE + (0x14 << 2))

#define SCR_INTEN2_TXTHRESHOLD_POS (0)
#define SCR_INTEN2_TXTHRESHOLD_MASK (0x1)

#define SCR_INTEN2_TCKERR_POS (1)
#define SCR_INTEN2_TCKERR_MASK (0x1)

#define SCR_INTEN2_RESERVED_2_15_POS (2)
#define SCR_INTEN2_RESERVED_2_15_MASK (0x3fff)

#define SCR_INTEN2_RESERVED_BIT_16_31_POS (16)
#define SCR_INTEN2_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_INTSTAT2_ADDR (SOC_SCR_REG_BASE + (0x15 << 2))

#define SCR_INTSTAT2_TXTHRESHOLD_POS (0)
#define SCR_INTSTAT2_TXTHRESHOLD_MASK (0x1)

#define SCR_INTSTAT2_TCKERR_POS (1)
#define SCR_INTSTAT2_TCKERR_MASK (0x1)

#define SCR_INTSTAT2_RESERVED_2_15_POS (2)
#define SCR_INTSTAT2_RESERVED_2_15_MASK (0x3fff)

#define SCR_INTSTAT2_RESERVED_BIT_16_31_POS (16)
#define SCR_INTSTAT2_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_TX_FIFO_THRESHOLD_ADDR (SOC_SCR_REG_BASE + (0x16 << 2))

#define SCR_TX_FIFO_THRESHOLD_TX_FIFO_THD_POS (0)
#define SCR_TX_FIFO_THRESHOLD_TX_FIFO_THD_MASK (0xffff)

#define SCR_TX_FIFO_THRESHOLD_RESERVED_BIT_16_31_POS (16)
#define SCR_TX_FIFO_THRESHOLD_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_TX_FIFO_COUNTER_ADDR (SOC_SCR_REG_BASE + (0x17 << 2))

#define SCR_TX_FIFO_COUNTER_TX_FIFO_CNT_POS (0)
#define SCR_TX_FIFO_COUNTER_TX_FIFO_CNT_MASK (0xffff)

#define SCR_TX_FIFO_COUNTER_RESERVED_BIT_16_31_POS (16)
#define SCR_TX_FIFO_COUNTER_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_RX_FIFO_COUNTER_ADDR (SOC_SCR_REG_BASE + (0x18 << 2))

#define SCR_RX_FIFO_COUNTER_RX_FIFO_CNT_POS (0)
#define SCR_RX_FIFO_COUNTER_RX_FIFO_CNT_MASK (0xffff)

#define SCR_RX_FIFO_COUNTER_RESERVED_BIT_16_31_POS (16)
#define SCR_RX_FIFO_COUNTER_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_BAUD_TUNE_REGISTER_ADDR (SOC_SCR_REG_BASE + (0x19 << 2))

#define SCR_BAUD_TUNE_REGISTER_BAUD_TUNE_REG_POS (0)
#define SCR_BAUD_TUNE_REGISTER_BAUD_TUNE_REG_MASK (0x7)

#define SCR_BAUD_TUNE_REGISTER_RESERVED_3_15_POS (3)
#define SCR_BAUD_TUNE_REGISTER_RESERVED_3_15_MASK (0x1fff)

#define SCR_BAUD_TUNE_REGISTER_RESERVED_BIT_16_31_POS (16)
#define SCR_BAUD_TUNE_REGISTER_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_ADDR (SOC_SCR_REG_BASE + (0x1a << 2))

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_TWO_CHAR_DELAY_LIMIT_H_POS (0)
#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_TWO_CHAR_DELAY_LIMIT_H_MASK (0xff)

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_RESERVED_8_15_POS (8)
#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_RESERVED_8_15_MASK (0xff)

#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_RESERVED_BIT_16_31_POS (16)
#define SCR_TWO_CHARACTERS_DELAY_LIMIT_H_RESERVED_BIT_16_31_MASK (0xffff)

#define SCR_FIFO_ADDR (SOC_SCR_REG_BASE + (0x80 << 2))

#define SCR_FIFO_FIFO_POS (0)
#define SCR_FIFO_FIFO_MASK (0xff)

#define SCR_FIFO_RESERVED_8_15_POS (8)
#define SCR_FIFO_RESERVED_8_15_MASK (0xff)

#define SCR_FIFO_RESERVED_BIT_16_31_POS (16)
#define SCR_FIFO_RESERVED_BIT_16_31_MASK (0xffff)

#ifdef __cplusplus
}
#endif
