// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define TRX__ADDR (SOC_TRX_REG_BASE + (0x0 << 2))

#define TRX__NC_0_31_POS (0)
#define TRX__NC_0_31_MASK (0xffffffff)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ADDR (SOC_TRX_REG_BASE + (0x1 << 2))

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BYPASS_OPT_POS (0)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BYPASS_OPT_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_MANUAL_BAND_POS (1)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_MANUAL_BAND_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BP_IBIAS_POS (2)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BP_IBIAS_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_VSEL1V_VCOLDO_POS (3)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_VSEL1V_VCOLDO_MASK (0x7)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_EDGESEL_NCK_POS (6)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_EDGESEL_NCK_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ICPOFFSET_TX_POS (7)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ICPOFFSET_TX_MASK (0x3f)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ITUNE_MIXER_POS (13)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ITUNE_MIXER_MASK (0x7)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ICPOFFSET_RX_POS (16)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_ICPOFFSET_RX_MASK (0x3f)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_CTUNE_LPF_POS (22)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_CTUNE_LPF_MASK (0x3f)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_NLOAD_DLYEN_POS (28)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_NLOAD_DLYEN_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_CALDONE_SPI_POS (29)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_CALDONE_SPI_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BYPASS_CALDONE_POS (30)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_BYPASS_CALDONE_MASK (0x1)

#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_VCTRL_CAL_POS (31)
#define TRX_CONTROLLING THE VOLTAGE OF CALIBRATION_VCTRL_CAL_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_ADDR (SOC_TRX_REG_BASE + (0x2 << 2))

#define TRX_ENABLE VCO IN THE TOP BY SPI_CK2XEN_POS (0)
#define TRX_ENABLE VCO IN THE TOP BY SPI_CK2XEN_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_CLKSEL_CAL_POS (1)
#define TRX_ENABLE VCO IN THE TOP BY SPI_CLKSEL_CAL_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_BANDCAL_SPI_POS (2)
#define TRX_ENABLE VCO IN THE TOP BY SPI_BANDCAL_SPI_MASK (0x3ff)

#define TRX_ENABLE VCO IN THE TOP BY SPI_BAND_SPI_TRGGER_POS (12)
#define TRX_ENABLE VCO IN THE TOP BY SPI_BAND_SPI_TRGGER_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_ICP_BIAS_COM_POS (13)
#define TRX_ENABLE VCO IN THE TOP BY SPI_ICP_BIAS_COM_MASK (0x3)

#define TRX_ENABLE VCO IN THE TOP BY SPI_HVREF_POS (15)
#define TRX_ENABLE VCO IN THE TOP BY SPI_HVREF_MASK (0x3)

#define TRX_ENABLE VCO IN THE TOP BY SPI_LVREF_POS (17)
#define TRX_ENABLE VCO IN THE TOP BY SPI_LVREF_MASK (0x3)

#define TRX_ENABLE VCO IN THE TOP BY SPI_DONE_DELAY_POS (19)
#define TRX_ENABLE VCO IN THE TOP BY SPI_DONE_DELAY_MASK (0x7)

#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPTRIGGER_POS (22)
#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPTRIGGER_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPAUTOCAL_POS (23)
#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPAUTOCAL_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPCAL_EN_POS (24)
#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPCAL_EN_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPCTRL_M_POS (25)
#define TRX_ENABLE VCO IN THE TOP BY SPI_AMPCTRL_M_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_ERRDET_EN_POS (26)
#define TRX_ENABLE VCO IN THE TOP BY SPI_ERRDET_EN_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_ERRDET_SPIEN_POS (27)
#define TRX_ENABLE VCO IN THE TOP BY SPI_ERRDET_SPIEN_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_VSEL1V_PLLLDO_POS (28)
#define TRX_ENABLE VCO IN THE TOP BY SPI_VSEL1V_PLLLDO_MASK (0x3)

#define TRX_ENABLE VCO IN THE TOP BY SPI_PLLEN_POS (30)
#define TRX_ENABLE VCO IN THE TOP BY SPI_PLLEN_MASK (0x1)

#define TRX_ENABLE VCO IN THE TOP BY SPI_VCOEN_POS (31)
#define TRX_ENABLE VCO IN THE TOP BY SPI_VCOEN_MASK (0x1)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ADDR (SOC_TRX_REG_BASE + (0x3 << 2))

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_CTUNE_MIXER_CH_POS (0)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_CTUNE_MIXER_CH_MASK (0xf)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_CTUNE_MIXER_POS (4)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_CTUNE_MIXER_MASK (0x3f)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_AMPSELU_POS (10)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_AMPSELU_MASK (0x7)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ICPBIAS_RX_POS (13)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ICPBIAS_RX_MASK (0x1)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ICPBIAS_TX_POS (14)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ICPBIAS_TX_MASK (0x1)

#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ITUNE_VCO_SPI_POS (15)
#define TRX_CONTROLLING THE BIAS CURRENT OF VCO_ITUNE_VCO_SPI_MASK (0x1ffff)

#define TRX_LOOP INT MODE ENABLE_ADDR (SOC_TRX_REG_BASE + (0x4 << 2))

#define TRX_LOOP INT MODE ENABLE_ICPBIAS_RX_POS (0)
#define TRX_LOOP INT MODE ENABLE_ICPBIAS_RX_MASK (0xf)

#define TRX_LOOP INT MODE ENABLE_ICPBIAS_TX_POS (4)
#define TRX_LOOP INT MODE ENABLE_ICPBIAS_TX_MASK (0xf)

#define TRX_LOOP INT MODE ENABLE_AMPSEL_POS (8)
#define TRX_LOOP INT MODE ENABLE_AMPSEL_MASK (0x1f)

#define TRX_LOOP INT MODE ENABLE_BYPASS_AAC_POS (13)
#define TRX_LOOP INT MODE ENABLE_BYPASS_AAC_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_RESET_SPI_POS (14)
#define TRX_LOOP INT MODE ENABLE_RESET_SPI_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_NRSTEN_POS (15)
#define TRX_LOOP INT MODE ENABLE_NRSTEN_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_TRISTATE_SPI_POS (16)
#define TRX_LOOP INT MODE ENABLE_TRISTATE_SPI_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_SELVCOPOL_POS (17)
#define TRX_LOOP INT MODE ENABLE_SELVCOPOL_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_NCLKEN_SPI_POS (18)
#define TRX_LOOP INT MODE ENABLE_NCLKEN_SPI_MASK (0x1)

#define TRX_LOOP INT MODE ENABLE_NINT_POS (19)
#define TRX_LOOP INT MODE ENABLE_NINT_MASK (0x3ff)

#define TRX_LOOP INT MODE ENABLE_IB1V_LOMIXER_POS (29)
#define TRX_LOOP INT MODE ENABLE_IB1V_LOMIXER_MASK (0x3)

#define TRX_LOOP INT MODE ENABLE_INT_MODE_POS (31)
#define TRX_LOOP INT MODE ENABLE_INT_MODE_MASK (0x1)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_ADDR (SOC_TRX_REG_BASE + (0x5 << 2))

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_NSDMLSB_POS (0)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_NSDMLSB_MASK (0xff)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_CKSEL_SDM_POS (8)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_CKSEL_SDM_MASK (0x3)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VCTRL_CAL_POS (10)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VCTRL_CAL_MASK (0x1)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_LO_POS (11)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_LO_MASK (0x7)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_PNEN_POS (14)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_PNEN_MASK (0x1)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_SDM_RSTN_POS (15)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_SDM_RSTN_MASK (0x1)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_PLLLDO_POS (16)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_PLLLDO_MASK (0x7)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VCTRL_CAL_POS (19)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VCTRL_CAL_MASK (0x1)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_CPLDO_POS (20)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_VSEL1V_CPLDO_MASK (0x1f)

#define TRX_SET THE FREQUENCY CHANNEL BY SPI_CHSPI_POS (25)
#define TRX_SET THE FREQUENCY CHANNEL BY SPI_CHSPI_MASK (0x7f)

#define TRX_DCOC I PATH INPUT_ADDR (SOC_TRX_REG_BASE + (0x6 << 2))

#define TRX_DCOC I PATH INPUT_DPD_EN_POS (0)
#define TRX_DCOC I PATH INPUT_DPD_EN_MASK (0x1)

#define TRX_DCOC I PATH INPUT_NC_1_1_POS (1)
#define TRX_DCOC I PATH INPUT_NC_1_1_MASK (0x1)

#define TRX_DCOC I PATH INPUT_RX3S_POS (2)
#define TRX_DCOC I PATH INPUT_RX3S_MASK (0x1)

#define TRX_DCOC I PATH INPUT_NC_3_3_POS (3)
#define TRX_DCOC I PATH INPUT_NC_3_3_MASK (0x1)

#define TRX_DCOC I PATH INPUT_NC_4_9_POS (4)
#define TRX_DCOC I PATH INPUT_NC_4_9_MASK (0x3f)

#define TRX_DCOC I PATH INPUT_NC_10_15_POS (10)
#define TRX_DCOC I PATH INPUT_NC_10_15_MASK (0x3f)

#define TRX_DCOC I PATH INPUT_DCOCQ_POS (16)
#define TRX_DCOC I PATH INPUT_DCOCQ_MASK (0xff)

#define TRX_DCOC I PATH INPUT_DCOCI_POS (24)
#define TRX_DCOC I PATH INPUT_DCOCI_MASK (0xff)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_ADDR (SOC_TRX_REG_BASE + (0x7 << 2))

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DIG_DCOEN_POS (0)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DIG_DCOEN_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_SPILPFRXG_POS (1)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_SPILPFRXG_MASK (0xf)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_AUTORXIFGEN_POS (5)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_AUTORXIFGEN_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DCOC_CTL_POS (6)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DCOC_CTL_MASK (0x3)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXGS_POS (8)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXGS_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFTXTEST_G_POS (9)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFTXTEST_G_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_ADC_CKINV_POS (10)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_ADC_CKINV_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_G_POS (11)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_G_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_ABWS_EN_POS (12)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_ABWS_EN_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFTXTEST_B_POS (13)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFTXTEST_B_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_B_POS (14)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_B_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_BLE_POS (15)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_TXIF_2RD_BLE_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_ISEL_BUF_POS (16)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_ISEL_BUF_MASK (0x7)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_ISEL_OPA_POS (19)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_ISEL_OPA_MASK (0x7)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_DELAY_POS (22)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_DELAY_MASK (0x1f)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_CK_EDGE_POS (27)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_DAC_CK_EDGE_MASK (0x1)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFCAPCALQ_H2B_POS (28)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFCAPCALQ_H2B_MASK (0x3)

#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFCAPCALI_H2B_POS (30)
#define TRX_LPF I PATH CALIBIRATION INPUT (HIGH 2BITS)_LPFCAPCALI_H2B_MASK (0x3)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_ADDR (SOC_TRX_REG_BASE + (0x8 << 2))

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_LOTRIGSPI_POS (0)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_LOTRIGSPI_MASK (0x1)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RFPLL_NOTCH_RES_POS (1)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RFPLL_NOTCH_RES_MASK (0x7f)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_EN_WIFIPLL_POS (8)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_EN_WIFIPLL_MASK (0x1)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_GRSSI_B_POS (9)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_GRSSI_B_MASK (0x1)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_GRSSI_W_POS (10)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_GRSSI_W_MASK (0x1)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_IBS_POS (11)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_IBS_MASK (0x3)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_TSEL_POS (13)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_TSEL_MASK (0x3)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_TEN_POS (15)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_TEN_MASK (0x1)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_BLE_POS (16)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSI_BLE_MASK (0xf)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITL_POS (20)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITL_MASK (0xf)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITM_POS (24)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITM_MASK (0xf)

#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITH_POS (28)
#define TRX_RSSI HIGH THRESHOLD FOR WIFI_RSSITH_MASK (0xf)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ADDR (SOC_TRX_REG_BASE + (0x9 << 2))

#define TRX_LNA LOAD  CAPACITOR TUNNING_AGCRXFEEN_POS (0)
#define TRX_LNA LOAD  CAPACITOR TUNNING_AGCRXFEEN_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_GRXLNASPI_POS (1)
#define TRX_LNA LOAD  CAPACITOR TUNNING_GRXLNASPI_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_GRXI2VSPI_POS (3)
#define TRX_LNA LOAD  CAPACITOR TUNNING_GRXI2VSPI_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_VBSRXLO_POS (5)
#define TRX_LNA LOAD  CAPACITOR TUNNING_VBSRXLO_MASK (0x7)

#define TRX_LNA LOAD  CAPACITOR TUNNING_IBSRXI2V_POS (8)
#define TRX_LNA LOAD  CAPACITOR TUNNING_IBSRXI2V_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_VLOFASTSEL_POS (10)
#define TRX_LNA LOAD  CAPACITOR TUNNING_VLOFASTSEL_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ENCLIP_POS (11)
#define TRX_LNA LOAD  CAPACITOR TUNNING_ENCLIP_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ENFSR_POS (12)
#define TRX_LNA LOAD  CAPACITOR TUNNING_ENFSR_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_VSLNALDO_POS (13)
#define TRX_LNA LOAD  CAPACITOR TUNNING_VSLNALDO_MASK (0x7)

#define TRX_LNA LOAD  CAPACITOR TUNNING_GLNAR_POS (16)
#define TRX_LNA LOAD  CAPACITOR TUNNING_GLNAR_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_V2IS_POS (18)
#define TRX_LNA LOAD  CAPACITOR TUNNING_V2IS_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_LNAIS_POS (20)
#define TRX_LNA LOAD  CAPACITOR TUNNING_LNAIS_MASK (0x3)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ATT_SPI_POS (22)
#define TRX_LNA LOAD  CAPACITOR TUNNING_ATT_SPI_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ATT_MANU_EN_POS (23)
#define TRX_LNA LOAD  CAPACITOR TUNNING_ATT_MANU_EN_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_INR_POS (24)
#define TRX_LNA LOAD  CAPACITOR TUNNING_INR_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_LGLC_POS (25)
#define TRX_LNA LOAD  CAPACITOR TUNNING_LGLC_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_R_TUNE_POS (26)
#define TRX_LNA LOAD  CAPACITOR TUNNING_R_TUNE_MASK (0x1)

#define TRX_LNA LOAD  CAPACITOR TUNNING_ISRXREF_POS (27)
#define TRX_LNA LOAD  CAPACITOR TUNNING_ISRXREF_MASK (0x7)

#define TRX_LNA LOAD  CAPACITOR TUNNING_CLOADLNA_POS (30)
#define TRX_LNA LOAD  CAPACITOR TUNNING_CLOADLNA_MASK (0x3)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_ADDR (SOC_TRX_REG_BASE + (0xa << 2))

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNC_POS (0)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNC_MASK (0x3)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNL_POS (2)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNL_MASK (0x3)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNH_POS (4)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_DYGS_VBNH_MASK (0x3)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PABIASCGM_POS (6)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PABIASCGM_MASK (0x1)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VDLS_POS (7)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VDLS_MASK (0x7)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VDHS_POS (10)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VDHS_MASK (0x7)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA__VBPAS_POS (13)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA__VBPAS_MASK (0xf)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VBNLS_POS (17)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VBNLS_MASK (0xf)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VBNHS_POS (21)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_VBNHS_MASK (0xf)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENDYC_POS (25)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENDYC_MASK (0x1)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENCSDYL_POS (26)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENCSDYL_MASK (0x1)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENCSDYH_POS (27)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_ENCSDYH_MASK (0x1)

#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_DIBIASBG_POS (28)
#define TRX_MSB OF PROGRAMMING OF PA CURRENT  100UA + 25UA*#LSB, LSB AT REG11 BIT17_PA_DIBIASBG_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_ADDR (SOC_TRX_REG_BASE + (0xb << 2))

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCD_POS (0)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCD_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCC_POS (4)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCC_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCB_POS (8)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCB_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCA_POS (12)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PADCA_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_HVDHS_POS (16)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_HVDHS_MASK (0x1)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_DIA_POS (17)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_DIA_MASK (0x1)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_DMODLDOSEL_POS (18)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_DMODLDOSEL_MASK (0x7)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_DICS_POS (21)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_DICS_MASK (0x3)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_DI_POS (23)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_DI_MASK (0xf)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_ENCAPDY_POS (27)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_PAD_ENCAPDY_MASK (0x1)

#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_MODCA_POS (28)
#define TRX_MODULATOR OUTPUT TUNING CAP PROGRAMMING: +18FF/LSB (LOW Q NODES)_MODCA_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_ADDR (SOC_TRX_REG_BASE + (0xc << 2))

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_GMGAIN_POS (0)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_GMGAIN_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PADCTRL_POS (4)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PADCTRL_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PACTRL_POS (8)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PACTRL_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_RGM_POS (12)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_RGM_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_DGMDC_POS (16)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_DGMDC_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_MIXVSWB_POS (20)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_MIXVSWB_MASK (0x3)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_MIXVBH_POS (22)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_MIXVBH_MASK (0x3)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PA_DIBIASPT_POS (24)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PA_DIBIASPT_MASK (0xf)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PA_CAP_POS (28)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PA_CAP_MASK (0x7)

#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PAMAPEN_POS (31)
#define TRX_(0: SPI;  1: DIGITAL) POWER CONTROL ENABLE_PAMAPEN_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_ADDR (SOC_TRX_REG_BASE + (0xd << 2))

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_IPATCS_POS (0)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_IPATCS_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TSSIQRG_POS (1)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TSSIQRG_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_VREF_VBGS_POS (4)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_VREF_VBGS_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_VB_VDDGS_POS (5)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_VB_VDDGS_MASK (0x3)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TSSIRANGES_POS (7)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TSSIRANGES_MASK (0x3)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_EN_PCAL_POS (9)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_EN_PCAL_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_EN_IQCAL_POS (10)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_EN_IQCAL_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_ITAS_POS (11)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_ITAS_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_RCCALEN_POS (12)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_RCCALEN_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_DYOPBIAS_POS (13)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PA_DYOPBIAS_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_RXLO LDO_POS (16)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_RXLO LDO_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_HVDLS_POS (19)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_HVDLS_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_ENPADCAPBIAS_POS (20)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_ENPADCAPBIAS_MASK (0x1)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PAD_CAPBIASS_POS (21)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_PAD_CAPBIASS_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TXLO LDO_POS (24)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_TXLO LDO_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_LDODA_POS (27)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_LDODA_MASK (0x7)

#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_IPATCS_POS (30)
#define TRX_MSB OF PA CURRENT BIAS TEMPERATURE  SETTING , ANOTHER BITS AT 0X00[0]_IPATCS_MASK (0x3)

#define TRX_NC_ADDR (SOC_TRX_REG_BASE + (0xe << 2))

#define TRX_NC_DYGS_VBNC_2_POS (0)
#define TRX_NC_DYGS_VBNC_2_MASK (0x3)

#define TRX_NC_DYGS_VBNL_2_POS (2)
#define TRX_NC_DYGS_VBNL_2_MASK (0x3)

#define TRX_NC_DYGS_VBNH_2_POS (4)
#define TRX_NC_DYGS_VBNH_2_MASK (0x3)

#define TRX_NC_PABIASCGM_2_POS (6)
#define TRX_NC_PABIASCGM_2_MASK (0x1)

#define TRX_NC_PA_VDLS_2_POS (7)
#define TRX_NC_PA_VDLS_2_MASK (0x7)

#define TRX_NC_PA_VDHS_2_POS (10)
#define TRX_NC_PA_VDHS_2_MASK (0x7)

#define TRX_NC_PA__VBPAS_2_POS (13)
#define TRX_NC_PA__VBPAS_2_MASK (0xf)

#define TRX_NC_PA_VBNLS_2_POS (17)
#define TRX_NC_PA_VBNLS_2_MASK (0xf)

#define TRX_NC_PA_VBNHS_2_POS (21)
#define TRX_NC_PA_VBNHS_2_MASK (0xf)

#define TRX_NC_PA_ENDYC_2_POS (25)
#define TRX_NC_PA_ENDYC_2_MASK (0x1)

#define TRX_NC_PA_ENCSDYL_2_POS (26)
#define TRX_NC_PA_ENCSDYL_2_MASK (0x1)

#define TRX_NC_PA_ENCSDYH_2_POS (27)
#define TRX_NC_PA_ENCSDYH_2_MASK (0x1)

#define TRX_NC_NC_28_31_POS (28)
#define TRX_NC_NC_28_31_MASK (0xf)

#define TRX_0 = REST; 1=NORMAL WORK_ADDR (SOC_TRX_REG_BASE + (0x12 << 2))

#define TRX_0 = REST; 1=NORMAL WORK_IOPS_POS (0)
#define TRX_0 = REST; 1=NORMAL WORK_IOPS_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_FICTL_POS (1)
#define TRX_0 = REST; 1=NORMAL WORK_FICTL_MASK (0x7)

#define TRX_0 = REST; 1=NORMAL WORK_CGMBS_POS (4)
#define TRX_0 = REST; 1=NORMAL WORK_CGMBS_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_LDOIFSEL_POS (5)
#define TRX_0 = REST; 1=NORMAL WORK_LDOIFSEL_MASK (0x7)

#define TRX_0 = REST; 1=NORMAL WORK_ENCLIP_FLT_POS (8)
#define TRX_0 = REST; 1=NORMAL WORK_ENCLIP_FLT_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_ENFSR_FLT_POS (9)
#define TRX_0 = REST; 1=NORMAL WORK_ENFSR_FLT_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_FLAGSEL_POS (10)
#define TRX_0 = REST; 1=NORMAL WORK_FLAGSEL_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_LDOAD_POS (11)
#define TRX_0 = REST; 1=NORMAL WORK_LDOAD_MASK (0x7)

#define TRX_0 = REST; 1=NORMAL WORK_ADC_ISEL_POS (14)
#define TRX_0 = REST; 1=NORMAL WORK_ADC_ISEL_MASK (0x7)

#define TRX_0 = REST; 1=NORMAL WORK_DLYPC_I_POS (17)
#define TRX_0 = REST; 1=NORMAL WORK_DLYPC_I_MASK (0x3)

#define TRX_0 = REST; 1=NORMAL WORK_TDTUNE_I_POS (19)
#define TRX_0 = REST; 1=NORMAL WORK_TDTUNE_I_MASK (0x3f)

#define TRX_0 = REST; 1=NORMAL WORK_TDTUNEB_POS (25)
#define TRX_0 = REST; 1=NORMAL WORK_TDTUNEB_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_CALEN_POS (26)
#define TRX_0 = REST; 1=NORMAL WORK_CALEN_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_CALNSEL_POS (27)
#define TRX_0 = REST; 1=NORMAL WORK_CALNSEL_MASK (0x3)

#define TRX_0 = REST; 1=NORMAL WORK_CKMODE_POS (29)
#define TRX_0 = REST; 1=NORMAL WORK_CKMODE_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_VREFS_POS (30)
#define TRX_0 = REST; 1=NORMAL WORK_VREFS_MASK (0x1)

#define TRX_0 = REST; 1=NORMAL WORK_ADC_RSTN_POS (31)
#define TRX_0 = REST; 1=NORMAL WORK_ADC_RSTN_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_ADDR (SOC_TRX_REG_BASE + (0x13 << 2))

#define TRX_CELL DELAY CONTROL SPI VALUE_LPFOUTTSTEN_POS (0)
#define TRX_CELL DELAY CONTROL SPI VALUE_LPFOUTTSTEN_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LPFINTSTEN_POS (1)
#define TRX_CELL DELAY CONTROL SPI VALUE_LPFINTSTEN_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_ATSEL_POS (2)
#define TRX_CELL DELAY CONTROL SPI VALUE_ATSEL_MASK (0x3)

#define TRX_CELL DELAY CONTROL SPI VALUE_ENTST_POS (4)
#define TRX_CELL DELAY CONTROL SPI VALUE_ENTST_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_NC_5_5_POS (5)
#define TRX_CELL DELAY CONTROL SPI VALUE_NC_5_5_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOVCTRL_TESTEN_POS (6)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOVCTRL_TESTEN_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOVCTRLSEL_POS (7)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOVCTRLSEL_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_TRSW_BT_MODE_POS (8)
#define TRX_CELL DELAY CONTROL SPI VALUE_TRSW_BT_MODE_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_BTPLL_EN_SPI_POS (9)
#define TRX_CELL DELAY CONTROL SPI VALUE_BTPLL_EN_SPI_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_NC_10_10_POS (10)
#define TRX_CELL DELAY CONTROL SPI VALUE_NC_10_10_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_T0R1_SPI_POS (11)
#define TRX_CELL DELAY CONTROL SPI VALUE_T0R1_SPI_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOTRIGCTR_POS (12)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOTRIGCTR_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOSEL_RX_POS (13)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOSEL_RX_MASK (0x3)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOSELVCTR_POS (15)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOSELVCTR_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_LOSEL0DIG_POS (16)
#define TRX_CELL DELAY CONTROL SPI VALUE_LOSEL0DIG_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_CKMODE_PWD_POS (17)
#define TRX_CELL DELAY CONTROL SPI VALUE_CKMODE_PWD_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_VBIAS_ADC_POS (18)
#define TRX_CELL DELAY CONTROL SPI VALUE_VBIAS_ADC_MASK (0x1f)

#define TRX_CELL DELAY CONTROL SPI VALUE_DLYPC_I_POS (23)
#define TRX_CELL DELAY CONTROL SPI VALUE_DLYPC_I_MASK (0x3)

#define TRX_CELL DELAY CONTROL SPI VALUE_NC_25_25_POS (25)
#define TRX_CELL DELAY CONTROL SPI VALUE_NC_25_25_MASK (0x1)

#define TRX_CELL DELAY CONTROL SPI VALUE_TDTUNE_Q_POS (26)
#define TRX_CELL DELAY CONTROL SPI VALUE_TDTUNE_Q_MASK (0x3f)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_ADDR (SOC_TRX_REG_BASE + (0x14 << 2))

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_NC_0_0_POS (0)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_NC_0_0_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_NC_1_1_POS (1)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_NC_1_1_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_WIFI_LOEN_POS (2)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_WIFI_LOEN_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_DIFFN_POS (3)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_DIFFN_MASK (0xffffff)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_PNEN_POS (27)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_PNEN_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_IF2M_POS (28)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_IF2M_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_RXLO_POS (29)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_RXLO_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_CKSEL_SDM_POS (30)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_CKSEL_SDM_MASK (0x1)

#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_CK2SDMPOL_SEL_POS (31)
#define TRX_CLOCK(TO SDM) POLARITY SELECTION.
          0:  NEGEDGE 
          1:  POSEDGE_CK2SDMPOL_SEL_MASK (0x1)

#define TRX__ADDR (SOC_TRX_REG_BASE + (0x15 << 2))

#define TRX__RESET_NLOAD_POS (0)
#define TRX__RESET_NLOAD_MASK (0x1)

#define TRX__TRISTATE_POS (1)
#define TRX__TRISTATE_MASK (0x1)

#define TRX__SELPOL_POS (2)
#define TRX__SELPOL_MASK (0x1)

#define TRX__NC_3_7_POS (3)
#define TRX__NC_3_7_MASK (0x1f)

#define TRX__CP1_RX_POS (8)
#define TRX__CP1_RX_MASK (0xf)

#define TRX__RP3_RX_POS (12)
#define TRX__RP3_RX_MASK (0xf)

#define TRX__RP2_RX_POS (16)
#define TRX__RP2_RX_MASK (0xf)

#define TRX__RP1_RX_POS (20)
#define TRX__RP1_RX_MASK (0x1f)

#define TRX__IOFFSET_RX_POS (25)
#define TRX__IOFFSET_RX_MASK (0x3)

#define TRX__ICP_RX_POS (27)
#define TRX__ICP_RX_MASK (0xf)

#define TRX__CK_NLOAD_EDGESEL_POS (31)
#define TRX__CK_NLOAD_EDGESEL_MASK (0x1)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._ADDR (SOC_TRX_REG_BASE + (0x16 << 2))

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._VREFLCTRL_POS (0)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._VREFLCTRL_MASK (0x3)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._VREFHCTRL_POS (2)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._VREFHCTRL_MASK (0x3)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._RESET_NCOUNTER_POS (4)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._RESET_NCOUNTER_MASK (0x1)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._NC_5_28_POS (5)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._NC_5_28_MASK (0xffffff)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._PWD5G_POS (29)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._PWD5G_MASK (0x1)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._PWD2G_POS (30)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._PWD2G_MASK (0x1)

#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._BP_OPT_POS (31)
#define TRX_BAND CALIBRATION OPTIMIZE ENABLE._BP_OPT_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_ADDR (SOC_TRX_REG_BASE + (0x17 << 2))

#define TRX_N VALUE SPI CONTROL_RCTRL_POS (0)
#define TRX_N VALUE SPI CONTROL_RCTRL_MASK (0xf)

#define TRX_N VALUE SPI CONTROL_PWD_VCOAMPCAL_POS (4)
#define TRX_N VALUE SPI CONTROL_PWD_VCOAMPCAL_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_RXLOCTRL_VCOCAL_POS (5)
#define TRX_N VALUE SPI CONTROL_RXLOCTRL_VCOCAL_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_DONE_DELAY_POS (6)
#define TRX_N VALUE SPI CONTROL_DONE_DELAY_MASK (0x7)

#define TRX_N VALUE SPI CONTROL_SPI_TRIGGER_POS (9)
#define TRX_N VALUE SPI CONTROL_SPI_TRIGGER_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_ERRDET_SPIEN_POS (10)
#define TRX_N VALUE SPI CONTROL_ERRDET_SPIEN_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_CKREF_LOOP_SEL_POS (11)
#define TRX_N VALUE SPI CONTROL_CKREF_LOOP_SEL_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_CKREF_NL_SEL_POS (12)
#define TRX_N VALUE SPI CONTROL_CKREF_NL_SEL_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_NRSTEN_POS (13)
#define TRX_N VALUE SPI CONTROL_NRSTEN_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_INT_MOD_POS (14)
#define TRX_N VALUE SPI CONTROL_INT_MOD_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_BAND_MEN_POS (15)
#define TRX_N VALUE SPI CONTROL_BAND_MEN_MASK (0x1)

#define TRX_N VALUE SPI CONTROL_BAND_SPI_POS (16)
#define TRX_N VALUE SPI CONTROL_BAND_SPI_MASK (0xff)

#define TRX_N VALUE SPI CONTROL_NMANUAL_POS (24)
#define TRX_N VALUE SPI CONTROL_NMANUAL_MASK (0xff)

#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._ADDR (SOC_TRX_REG_BASE + (0x18 << 2))

#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._NC_0_19_POS (0)
#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._NC_0_19_MASK (0xfffff)

#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOBIAS_MEN_POS (20)
#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOBIAS_MEN_MASK (0x1)

#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOBIAS_SPI_POS (21)
#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOBIAS_SPI_MASK (0x3f)

#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOAMPDET_POS (27)
#define TRX_VCO AMPLITUDE AUTO CALIBRATION THRESHOLD CONTROL.._VCOAMPDET_MASK (0x1f)

#define TRX__ADDR (SOC_TRX_REG_BASE + (0x19 << 2))

#define TRX__NC_0_1_POS (0)
#define TRX__NC_0_1_MASK (0x3)

#define TRX__BWCTRL_POS (2)
#define TRX__BWCTRL_MASK (0x1)

#define TRX__NC_3_3_POS (3)
#define TRX__NC_3_3_MASK (0x1)

#define TRX__VCOHPEN_POS (4)
#define TRX__VCOHPEN_MASK (0x1)

#define TRX__NC_5_12_POS (5)
#define TRX__NC_5_12_MASK (0xff)

#define TRX__VCAL_SEL_POS (13)
#define TRX__VCAL_SEL_MASK (0x3)

#define TRX__NC_15_20_POS (15)
#define TRX__NC_15_20_MASK (0x3f)

#define TRX__VSEL1V_VCO_POS (21)
#define TRX__VSEL1V_VCO_MASK (0x7)

#define TRX__VSEL1V_PLL_POS (24)
#define TRX__VSEL1V_PLL_MASK (0x7)

#define TRX__VSEL1V_CP_POS (27)
#define TRX__VSEL1V_CP_MASK (0x7)

#define TRX__NC_30_30_POS (30)
#define TRX__NC_30_30_MASK (0x1)

#define TRX__CK26M_40M_SEL_POS (31)
#define TRX__CK26M_40M_SEL_MASK (0x1)

#define TRX__ADDR (SOC_TRX_REG_BASE + (0x1a << 2))

#define TRX__NC_0_31_POS (0)
#define TRX__NC_0_31_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
